cuboid:
  obstacle0:
    dims: [0.2, 0.2, 0.2]
    pose: [0.4, -0.4, 0.33, 1.0, 0.0, 0.0, 0.0]
  obstacle1:
    dims: [0.2, 0.2, 0.2]
    pose: [0.4, -0.2, 0.33, 1.0, 0.0, 0.0, 0.0]
  obstacle2:
    dims: [0.2, 0.2, 0.2]
    pose: [0.4, 0.0, 0.33, 1.0, 0.0, 0.0, 0.0]
  obstacle3:
    dims: [0.2, 0.2, 0.2]
    pose: [0.4, 0.2, 0.33, 1.0, 0.0, 0.0, 0.0]
  obstacle4:
    dims: [0.2, 0.2, 0.2]
    pose: [0.4, 0.4, 0.33, 1.0, 0.0, 0.0, 0.0]
  obstacle5:
    dims: [0.2, 0.2, 0.2]
    pose: [0.4, -0.4, 0.8, 1.0, 0.0, 0.0, 0.0]
  obstacle6:
    dims: [0.2, 0.2, 0.2]
    pose: [0.4, -0.2, 0.8, 1.0, 0.0, 0.0, 0.0]
  obstacle7:
    dims: [0.2, 0.2, 0.2]
    pose: [0.4, 0.0, 0.8, 1.0, 0.0, 0.0, 0.0]
  obstacle8:
    dims: [0.2, 0.2, 0.2]
    pose: [0.4, 0.2, 0.8, 1.0, 0.0, 0.0, 0.0]
  obstacle9:
    dims: [0.2, 0.2, 0.2]
    pose: [0.4, 0.4, 0.8, 1.0, 0.0, 0.0, 0.0]
