cuboid:
  obstacle0:
    dims: [0.2, 0.2, 0.2]
    pose: [0.4, -0.4, 0.0, 1.0, 0.0, 0.0, 0.0]
  obstacle1:
    dims: [0.2, 0.2, 0.2]
    pose: [0.4, -0.2, 0.0, 1.0, 0.0, 0.0, 0.0]
  obstacle2:
    dims: [0.2, 0.2, 0.2]
    pose: [0.4, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0]
  obstacle3:
    dims: [0.2, 0.2, 0.2]
    pose: [0.4, 0.2, 0.0, 1.0, 0.0, 0.0, 0.0]
  obstacle4:
    dims: [0.2, 0.2, 0.2]
    pose: [0.4, 0.4, 0.0, 1.0, 0.0, 0.0, 0.0]
  obstacle5:
    dims: [0.2, 0.2, 0.2]
    pose: [0.4, -0.4, 0.5, 1.0, 0.0, 0.0, 0.0]
  obstacle6:
    dims: [0.2, 0.2, 0.2]
    pose: [0.4, -0.2, 0.5, 1.0, 0.0, 0.0, 0.0]
  obstacle7:
    dims: [0.2, 0.2, 0.2]
    pose: [0.4, 0.0, 0.5, 1.0, 0.0, 0.0, 0.0]
  obstacle8:
    dims: [0.2, 0.2, 0.2]
    pose: [0.4, 0.2, 0.5, 1.0, 0.0, 0.0, 0.0]
  obstacle9:
    dims: [0.2, 0.2, 0.2]
    pose: [0.4, 0.4, 0.5, 1.0, 0.0, 0.0, 0.0]
  obstacle10:
    dims: [0.2, 0.2, 0.2]
    pose: [0.4, -0.5, 0.7, 1.0, 0.0, 0.0, 0.0]
  obstacle11:
    dims: [0.2, 0.2, 0.2]
    pose: [0.4, 0.5, 0.7, 1.0, 0.0, 0.0, 0.0]
  obstacle12:
    dims: [0.2, 0.2, 0.2]
    pose: [0.4, 0.0, 0.7, 1.0, 0.0, 0.0, 0.0]
  obstacle13:
    dims: [0.2, 0.2, 0.2]
    pose: [0.4, 0.0, 0.9, 1.0, 0.0, 0.0, 0.0]
