cuboid:
  obstacle0:
    dims: [0.2, 0.2, 0.2]
    pose: [0.5, 0.0, -0.4, 1.0, 0.0, 0.0, 0.0]
  obstacle1:
    dims: [0.2, 0.2, 0.2]
    pose: [0.5, 0.0, -0.2, 1.0, 0.0, 0.0, 0.0]
  obstacle2:
    dims: [0.2, 0.2, 0.2]
    pose: [0.5, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0]
  obstacle3:
    dims: [0.2, 0.2, 0.2]
    pose: [0.5, 0.0, 0.2, 1.0, 0.0, 0.0, 0.0]
  obstacle4:
    dims: [0.2, 0.2, 0.2]
    pose: [0.5, 0.0, 0.4, 1.0, 0.0, 0.0, 0.0]
