## SPDX-FileCopyrightText: Copyright (c) 2023-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
## SPDX-License-Identifier: Apache-2.0
robot_cfg:
  dynamics:
    neural_inverse_dynamics_state_dict: inverse_dynamics/ur10e.pt
    payload_joint: wrist_3_joint
    payload_mass_range:
    - 0.0
    - 10.0
  kinematics:
    asset_root_path: robot/ur_description
    base_link: base_link
    collision_link_names:
    - shoulder_link
    - upper_arm_link
    - forearm_link
    - wrist_1_link
    - wrist_2_link
    - wrist_3_link
    - tool0
    collision_sphere_buffer: 0.0
    collision_spheres:
      shoulder_link:
        - center: [0, 0, 0]
          radius: 0.05
      upper_arm_link:
        - center: [-0, -0, 0.18]
          radius: 0.09
        - center: [-0.102167, 0, 0.18]
          radius: 0.05
        - center: [-0.204333, 0, 0.18]
          radius: 0.05
        - center: [-0.3065, 0, 0.18]
          radius: 0.05
        - center: [-0.408667, 0, 0.18]
          radius: 0.05
        - center: [-0.510833, 0, 0.18]
          radius: 0.05
        - center: [-0.613, 0, 0.18]
          radius: 0.07
      forearm_link:
        - center: [-0, 0, 0.03]
          radius: 0.05
        - center: [-0.0951667, 0, 0.03]
          radius: 0.05
        - center: [-0.190333, 0, 0.03]
          radius: 0.05
        - center: [-0.2855, 0, 0.03]
          radius: 0.05
        - center: [-0.380667, 0, 0.03]
          radius: 0.05
        - center: [-0.475833, 0, 0.03]
          radius: 0.05
        - center: [-0.571, 0, 0.03]
          radius: 0.05
      wrist_1_link:
        - center: [0, 0, 0]
          radius: 0.05
      wrist_2_link:
        - center: [0, 0, 0]
          radius: 0.05
      wrist_3_link:
        - center: [0, 0, 0]
          radius: 0.05
        - center: [0, 0, 0.06]
          radius: 0.07
      tool0:
        - center: [0, 0, 0.12]
          radius: -0.01
      camera_mount:
        - center: [0, 0.11, -0.01]
          radius: 0.06
    cspace:
      cspace_distance_weight:
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      joint_names:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
      max_acceleration: 12.0
      max_jerk: 500.0
      null_space_weight:
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      position_limit_clip: 0.1
      default_joint_position:
      - 0.0
      - -2.2
      - 1.9
      - -1.383
      - -1.57
      - 0.0
    tool_frames:
    - tool0
    lock_joints: null
    mesh_link_names:
    - shoulder_link
    - upper_arm_link
    - forearm_link
    - wrist_1_link
    - wrist_2_link
    - wrist_3_link
    self_collision_buffer:
      forearm_link: 0
      shoulder_link: 0.07
      tool0: 0.0 # 0.05
      upper_arm_link: 0
      wrist_1_link: 0
      wrist_2_link: 0
      wrist_3_link: 0
    self_collision_ignore:
      #shoulder_link:
      #- base_link
      camera_mount:
      - tool0
      - wrist_3_link
      forarm_link:
      - wrist_1_link
      upper_arm_link:
      - forearm_link
      - shoulder_link
      wrist_1_link:
      - wrist_2_link
      - wrist_3_link
      wrist_2_link:
      - wrist_3_link
      - tool0
      wrist_3_link:
      - tool0
    urdf_path: robot/ur_description/ur10e.urdf
