##
## Copyright (c) 2023 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
##
## NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
## property and proprietary rights in and to this material, related
## documentation and any modifications thereto. Any use, reproduction,
## disclosure or distribution of this material and related documentation
## without an express license agreement from NVIDIA CORPORATION or
## its affiliates is strictly prohibited.
##

robot_cfg:
  kinematics:
    usd_path: "robot/flexiv_description/flexiv.usd"
    usd_robot_root: "/robot"
    isaac_usd_path: ""
    usd_flip_joints: {}
    usd_flip_joint_limits: []

    urdf_path: "robot/flexiv_description/flexiv.urdf"
    asset_root_path: "robot/flexiv_description"
    
    base_link: "world"
    ee_link: "ee_target"
    link_names: null #["link1,link2,link3,link4,link5,link6,link7"]
    lock_joints: null
    extra_links: null

    
    collision_link_names: ["link1","link2","link3","link4","link5","link6","link7"]
    collision_spheres: "spheres/flexiv_raw_spheres.yaml"
      
    collision_sphere_buffer: 0.005
    extra_collision_spheres: {}
    self_collision_ignore: {
    "link1":["link2"],
    "link2":["link1","link3"],
    "link3":["link2","link4"],
    "link4":["link3","link5"],
    "link5":["link4","link6"],
    "link6":["link5","link7"],
    "link7":["link6"],
    }
    self_collision_buffer: {
    "link1":0,
    "link2":0,
    "link3":0,
    "link4":0,
    "link5":0,
    "link6":0,
    "link7":0,
    }

    use_global_cumul: True
    mesh_link_names: null # List[str]

    cspace:
      joint_names: ["joint1","joint2","joint3","joint4","joint5","joint6","joint7"] # List[str]
      retract_config: [0.0, -0.698, 0.0, 1.5708, 0.0, 0.698, 0.0] # List[float]
      null_space_weight: [1.0,1.0,1.0,1.0,1.0,1.0,1.0] # List[str]
      cspace_distance_weight: [1.0,1.0,1.0,1.0,1.0,1.0,1.0] # List[str]
      max_jerk: 500.0
      max_acceleration: 15.0
