## SPDX-FileCopyrightText: Copyright (c) 2023-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
## SPDX-License-Identifier: Apache-2.0
rollout:
  cost_cfg:
    bound_cfg:
      activation_distance:
      - 0.001
      - 0.001

      weight:
      - 50.0
      - 1.0
      cost_type: TELEPORT

    multi_link_pose_cfg:
      _project_distance_to_goal: false
      weight:
        - 1000.0
        - 10.0

      _terminal_pose_convergence_tolerance:
        - 1.0e-8 #1.0e-8 #1.0e-8
        - 1.0e-8 #1.0e-6
      use_grad_input: false
      use_lie_group: false

  constraint_cfg:
    scene_collision_cfg:
      activation_distance: 0.01
      use_sweep: false
      weight: 500.0
    self_collision_cfg:
      weight: 50.0

optimizer:
  solver_type: "mppi"
  gamma: 1.0
  init_cov: 1.0
  kappa: 0.01
  beta: 1.0
  step_size_cov: 0.2
  step_size_mean: 0.9
  num_iters: 4
  inner_iters: 4
  num_problems: 1
  null_act_frac: 0.0
  num_particles: 25
  random_mean: false
  sample_mode:  BEST
  sample_params:
    filter_coeffs:
    - 0.0
    - 0.0
    - 1.0
    fixed_samples: true
    n_knots: 5
    sample_ratio:
      halton: 1.0
      halton-knot: 0.0
      random: 0.0
      random-knot: 0.0
    seed: 23
  sample_per_problem: true
  seed: 0
  squash_fn: CLAMP
  store_debug: false
  sync_cuda_time: false
  update_cov: true
  use_coo_sparse: true
