## SPDX-FileCopyrightText: Copyright (c) 2023-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
## SPDX-License-Identifier: Apache-2.0
cuboid:
  table:
    dims: [4.0, 4.0, 0.2] # x, y, z
    pose: [0.0, 0.0, -0.2, 1, 0, 0, 0.0] # x, y, z, qx, qy, qz, qw