collision_spheres:
  base_link:
    - "center": [0.0, 0.0, 0.06]
      "radius": 0.02
  link1:
    - "center": [0.0, 0.0, 0.02]
      "radius": 0.07
    - "center": [0.0, -0.015, 0.21]
      "radius": 0.075
    - "center": [0.0, -0.004, 0.066]
      "radius": 0.071
    - "center": [0.0, -0.007, 0.113]
      "radius": 0.072
    - "center": [0.0, -0.011, 0.161]
      "radius": 0.074
  link2:
    - "center": [0.0, 0.04, 0.01]
      "radius": 0.075
    - "center": [0.0, 0.035, 0.17]
      "radius": 0.06
    - "center": [0.0, 0.038, 0.067]
      "radius": 0.07
    - "center": [0.0, 0.037, 0.121]
      "radius": 0.065
  link3:
    - "center": [0.0, 0.0, 0.03]
      "radius": 0.06
    - "center": [-0.02, 0.01, 0.19]
      "radius": 0.065
    - "center": [-0.006, 0.003, 0.082]
      "radius": 0.062
    - "center": [-0.013, 0.007, 0.135]
      "radius": 0.063
  link4:
    - "center": [0.0, 0.04, 0.01]
      "radius": 0.065
    - "center": [-0.02, 0.025, 0.16]
      "radius": 0.06
    - "center": [-0.007, 0.035, 0.061]
      "radius": 0.063
    - "center": [-0.014, 0.03, 0.111]
      "radius": 0.062
  link5:
    - "center": [0.0, 0.0, 0.03]
      "radius": 0.06
    - "center": [0.0, -0.01, 0.19]
      "radius": 0.06
    - "center": [0.0, -0.002, 0.07]
      "radius": 0.06
    - "center": [0.0, -0.005, 0.11]
      "radius": 0.06
    - "center": [0.0, -0.008, 0.15]
      "radius": 0.06
  link6:
    - "center": [0.0, 0.035, 0.0]
      "radius": 0.07
    - "center": [0.03, 0.07, 0.11]
      "radius": 0.06
    - "center": [0.0, 0.053, 0.057]
      "radius": 0.065
    - "center": [-0.02, 0.07, 0.11]
      "radius": 0.06
  link7:
    - "center": [0.0, 0.0, 0.04]
      "radius": 0.05
    - "center": [0.0, 0.0, 0.0]
      "radius": 0.05
    - "center": [0.0, 0.0, 0.098]
      "radius": 0.03
    - "center": [0.0, 0.0, 0.186]
      "radius": 0.03
    - "center": [0.0, 0.0, 0.127]
      "radius": 0.03
    - "center": [0.0, 0.0, 0.156]
      "radius": 0.03
    - "center": [0.0, 0.035, 0.089]
      "radius": 0.015
    - "center": [0.0, 0.035, 0.115]
      "radius": 0.015
    - "center": [0.0, -0.035, 0.115]
      "radius": 0.015
    - "center": [0.0, -0.035, 0.089]
      "radius": 0.015
      #
    - "center": [0.0, 0.049, 0.257]
      "radius": 0.011
    - "center": [0.0, 0.051, 0.246]
      "radius": 0.011
    - "center": [0.0, 0.051, 0.233]
      "radius": 0.011
    - "center": [0.0, 0.073, 0.218]
      "radius": 0.01
    - "center": [0.0, 0.062, 0.203]
      "radius": 0.01
    - "center": [0.0, 0.059, 0.188]
      "radius": 0.01
    - "center": [0.0, 0.032, 0.164]
      "radius": 0.021
    - "center": [0.0, 0.053, 0.169]
      "radius": 0.014
    - "center": [0.0, 0.037, 0.207]
      "radius": 0.02
    - "center": [0.014, 0.025, 0.198]
      "radius": 0.015
    - "center": [-0.014, 0.025, 0.198]
      "radius": 0.015
      #
    - "center": [0.0, -0.049, 0.257]
      "radius": 0.011
    - "center": [0.0, -0.051, 0.246]
      "radius": 0.011
    - "center": [0.0, -0.051, 0.233]
      "radius": 0.011
    - "center": [0.0, -0.073, 0.218]
      "radius": 0.01
    - "center": [0.0, -0.062, 0.203]
      "radius": 0.01
    - "center": [0.0, -0.059, 0.188]
      "radius": 0.01
    - "center": [0.0, -0.032, 0.164]
      "radius": 0.021
    - "center": [0.0, -0.053, 0.169]
      "radius": 0.014
    - "center": [0.0, -0.037, 0.207]
      "radius": 0.02
    - "center": [0.014, -0.025, 0.198]
      "radius": 0.015
    - "center": [-0.014, -0.025, 0.198]
      "radius": 0.015
  base_link_1:
    - "center": [0.0, 0.0, 0.06]
      "radius": 0.02
  link1_1:
    - "center": [0.0, 0.0, 0.02]
      "radius": 0.07
    - "center": [0.0, -0.015, 0.21]
      "radius": 0.075
    - "center": [0.0, -0.004, 0.066]
      "radius": 0.071
    - "center": [0.0, -0.007, 0.113]
      "radius": 0.072
    - "center": [0.0, -0.011, 0.161]
      "radius": 0.074
  link2_1:
    - "center": [0.0, 0.04, 0.01]
      "radius": 0.075
    - "center": [0.0, 0.035, 0.17]
      "radius": 0.06
    - "center": [0.0, 0.038, 0.067]
      "radius": 0.07
    - "center": [0.0, 0.037, 0.121]
      "radius": 0.065
  link3_1:
    - "center": [0.0, 0.0, 0.03]
      "radius": 0.06
    - "center": [-0.02, 0.01, 0.19]
      "radius": 0.065
    - "center": [-0.006, 0.003, 0.082]
      "radius": 0.062
    - "center": [-0.013, 0.007, 0.135]
      "radius": 0.063
  link4_1:
    - "center": [0.0, 0.04, 0.01]
      "radius": 0.065
    - "center": [-0.02, 0.025, 0.16]
      "radius": 0.06
    - "center": [-0.007, 0.035, 0.061]
      "radius": 0.063
    - "center": [-0.014, 0.03, 0.111]
      "radius": 0.062
  link5_1:
    - "center": [0.0, 0.0, 0.03]
      "radius": 0.06
    - "center": [0.0, -0.01, 0.19]
      "radius": 0.06
    - "center": [0.0, -0.002, 0.07]
      "radius": 0.06
    - "center": [0.0, -0.005, 0.11]
      "radius": 0.06
    - "center": [0.0, -0.008, 0.15]
      "radius": 0.06
  link6_1:
    - "center": [0.0, 0.035, 0.0]
      "radius": 0.07
    - "center": [0.03, 0.07, 0.11]
      "radius": 0.06
    - "center": [0.0, 0.053, 0.057]
      "radius": 0.065
    - "center": [-0.02, 0.07, 0.11]
      "radius": 0.06
  link7_1:
    - "center": [0.0, 0.0, 0.04]
      "radius": 0.05
    - "center": [0.0, 0.0, 0.0]
      "radius": 0.05
    - "center": [0.0, 0.0, 0.098]
      "radius": 0.03
    - "center": [0.0, 0.0, 0.186]
      "radius": 0.03
    - "center": [0.0, 0.0, 0.127]
      "radius": 0.03
    - "center": [0.0, 0.0, 0.156]
      "radius": 0.03
    - "center": [0.0, 0.035, 0.089]
      "radius": 0.015
    - "center": [0.0, 0.035, 0.115]
      "radius": 0.015
    - "center": [0.0, -0.035, 0.115]
      "radius": 0.015
    - "center": [0.0, -0.035, 0.089]
      "radius": 0.015
      #
    - "center": [0.0, 0.049, 0.257]
      "radius": 0.011
    - "center": [0.0, 0.051, 0.246]
      "radius": 0.011
    - "center": [0.0, 0.051, 0.233]
      "radius": 0.011
    - "center": [0.0, 0.073, 0.218]
      "radius": 0.01
    - "center": [0.0, 0.062, 0.203]
      "radius": 0.01
    - "center": [0.0, 0.059, 0.188]
      "radius": 0.01
    - "center": [0.0, 0.032, 0.164]
      "radius": 0.021
    - "center": [0.0, 0.053, 0.169]
      "radius": 0.014
    - "center": [0.0, 0.037, 0.207]
      "radius": 0.02
    - "center": [0.014, 0.025, 0.198]
      "radius": 0.015
    - "center": [-0.014, 0.025, 0.198]
      "radius": 0.015
      #
    - "center": [0.0, -0.049, 0.257]
      "radius": 0.011
    - "center": [0.0, -0.051, 0.246]
      "radius": 0.011
    - "center": [0.0, -0.051, 0.233]
      "radius": 0.011
    - "center": [0.0, -0.073, 0.218]
      "radius": 0.01
    - "center": [0.0, -0.062, 0.203]
      "radius": 0.01
    - "center": [0.0, -0.059, 0.188]
      "radius": 0.01
    - "center": [0.0, -0.032, 0.164]
      "radius": 0.021
    - "center": [0.0, -0.053, 0.169]
      "radius": 0.014
    - "center": [0.0, -0.037, 0.207]
      "radius": 0.02
    - "center": [0.014, -0.025, 0.198]
      "radius": 0.015
    - "center": [-0.014, -0.025, 0.198]
      "radius": 0.015
