# The robot description defines the generalized coordinates and how to map those
# to the underlying URDF dofs.

api_version: 1.0

# Defines the generalized coordinates. Each generalized coordinate is assumed
# to have an entry in the URDF.
# Lula will only use these joints to control the robot position.
cspace:
    - joint1
default_q: [
    1e-04
]

# Most dimensions of the cspace have a direct corresponding element
# in the URDF. This list of rules defines how unspecified coordinates
# should be extracted or how values in the URDF should be overwritten.

cspace_to_urdf_rules:
    - {name: joint2, rule: fixed, value: -1e-04}
    - {name: joint3, rule: fixed, value: 0.0005}
    - {name: joint4, rule: fixed, value: 1e-04}
    - {name: joint5, rule: fixed, value: -0.0002}
    - {name: joint6, rule: fixed, value: -0.0}
    - {name: joint7, rule: fixed, value: -0.0}
    - {name: rightgripper_finger1_inner_knuckle_joint, rule: fixed, value: 0.0}
    - {name: rightgripper_finger2_inner_knuckle_joint, rule: fixed, value: -0.0}
    - {name: rightgripper_finger1_finger_tip_joint, rule: fixed, value: 0.0}
    - {name: rightgripper_finger2_finger_tip_joint, rule: fixed, value: 0.0}

# Lula uses collision spheres to define the robot geometry in order to avoid
# collisions with external obstacles.  If no spheres are specified, Lula will
# not be able to avoid obstacles.

collision_spheres:
  - link7:
    - "center": [0.0, 0.0, 0.04]
      "radius": 0.05
    - "center": [0.0, 0.0, 0.0]
      "radius": 0.05
    - "center": [0.0, 0.0, 0.098]
      "radius": 0.03
    - "center": [0.0, 0.0, 0.186]
      "radius": 0.03
    - "center": [0.0, 0.0, 0.127]
      "radius": 0.03
    - "center": [0.0, 0.0, 0.156]
      "radius": 0.03
    - "center": [0.0, 0.035, 0.089]
      "radius": 0.015
    - "center": [0.0, 0.035, 0.115]
      "radius": 0.015
    - "center": [0.0, -0.035, 0.115]
      "radius": 0.015
    - "center": [0.0, -0.035, 0.089]
      "radius": 0.015
      #
    - "center": [0.0, 0.049, 0.257]
      "radius": 0.011
    - "center": [0.0, 0.051, 0.246]
      "radius": 0.011
    - "center": [0.0, 0.051, 0.233]
      "radius": 0.011
    - "center": [0.0, 0.073, 0.218]
      "radius": 0.01
    - "center": [0.0, 0.062, 0.203]
      "radius": 0.01
    - "center": [0.0, 0.059, 0.188]
      "radius": 0.01
    - "center": [0.0, 0.032, 0.164]
      "radius": 0.021
    - "center": [0.0, 0.053, 0.169]
      "radius": 0.014
    - "center": [0.0, 0.037, 0.207]
      "radius": 0.02
    - "center": [0.014, 0.025, 0.198]
      "radius": 0.015
    - "center": [-0.014, 0.025, 0.198]
      "radius": 0.015
      #
    - "center": [0.0, -0.049, 0.257]
      "radius": 0.011
    - "center": [0.0, -0.051, 0.246]
      "radius": 0.011
    - "center": [0.0, -0.051, 0.233]
      "radius": 0.011
    - "center": [0.0, -0.073, 0.218]
      "radius": 0.01
    - "center": [0.0, -0.062, 0.203]
      "radius": 0.01
    - "center": [0.0, -0.059, 0.188]
      "radius": 0.01
    - "center": [0.0, -0.032, 0.164]
      "radius": 0.021
    - "center": [0.0, -0.053, 0.169]
      "radius": 0.014
    - "center": [0.0, -0.037, 0.207]
      "radius": 0.02
    - "center": [0.014, -0.025, 0.198]
      "radius": 0.015
    - "center": [-0.014, -0.025, 0.198]
      "radius": 0.015
