robot: 'sr_hand_ur10e_right'
collision_spheres:
  ra_shoulder_link:
    - "center": [0.0, 0.0, 0.0]
      "radius": 0.108
  ra_upper_arm_link:
    - "center": [0.0, 0.0, 0.18]
      "radius": 0.11
    - "center": [-0.605, 0.0, 0.18]
      "radius": 0.086
    - "center": [-0.101, 0.0, 0.18]
      "radius": 0.08
    - "center": [-0.202, 0.0, 0.18]
      "radius": 0.08
    - "center": [-0.303, 0.0, 0.18]
      "radius": 0.08
    - "center": [-0.403, 0.0, 0.18]
      "radius": 0.08
    - "center": [-0.504, 0.0, 0.18]
      "radius": 0.08
  ra_forearm_link:
    - "center": [0.0, 0.0, 0.045]
      "radius": 0.08
    - "center": [-0.543, 0.0, 0.045]
      "radius": 0.079
    - "center": [-0.09, 0.0, 0.045]
      "radius": 0.065
    - "center": [-0.181, 0.0, 0.045]
      "radius": 0.065
    - "center": [-0.271, 0.0, 0.045]
      "radius": 0.065
    - "center": [-0.362, 0.0, 0.045]
      "radius": 0.065
    - "center": [-0.452, 0.0, 0.045]
      "radius": 0.065
  ra_wrist_1_link:
    - "center": [-0.0, 0.0, 0.0]
      "radius": 0.067
  ra_wrist_2_link:
    - "center": [-0.0, 0.008, -0.0]
      "radius": 0.07
  ra_wrist_3_link:
    - "center": [0.0, 0.0, -0.024]
      "radius": 0.05
  rh_forearm:
    - "center": [-0.0, -0.0, 0.051]
      "radius": 0.079
    - "center": [-0.0, 0.0, 0.142]
      "radius": 0.079
  rh_palm:
    - "center": [-0.021, 0.0, 0.0]
      "radius": 0.02
    - "center": [-0.021, 0.0, 0.176]
      "radius": 0.02
    - "center": [-0.021, 0.0, 0.035]
      "radius": 0.02
    - "center": [-0.021, 0.0, 0.07]
      "radius": 0.02
    - "center": [-0.021, 0.0, 0.106]
      "radius": 0.02
    - "center": [-0.021, 0.0, 0.141]
      "radius": 0.02
    - "center": [0.027, 0.0, 0.0]
      "radius": 0.02
    - "center": [0.027, 0.0, 0.182]
      "radius": 0.02
    - "center": [0.027, 0.0, 0.036]
      "radius": 0.02
    - "center": [0.027, 0.0, 0.073]
      "radius": 0.02
    - "center": [0.027, 0.0, 0.109]
      "radius": 0.02
    - "center": [0.027, 0.0, 0.146]
      "radius": 0.02
